### ISSUE TITLE
libGL error on Ubuntu upon GUI start-up

### ISSUE THREAD

**Issue by taltman** [hallamlab/metapathways2#18]
When I fire up the GUI, I get an ominous error loading swrast driver. It doesn't crash the GUI, though. It loads just fine. Info below:

---

taltman1@corn02:~/farmshare/third-party/bin/MetaPathways/v2.5$ ./metapathways2-master/MetaPathways2.Ubuntu/MetaPathways2 &
[1] 33595
taltman1@corn02:~/farmshare/third-party/bin/MetaPathways/v2.5$ Xlib:  extension "RANDR" missing on display "localhost:10.0".
libGL error: failed to load driver: swrast

taltman1@corn02:~/farmshare/third-party/bin/MetaPathways/v2.5$ uname -a
Linux corn02.stanford.edu 3.13.0-36-generic #63-Ubuntu SMP Wed Sep 3 21:30:07 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

**Comment by hallamlab** [comment]
I tested 3.0 and did not see this error. thanks!
