### ISSUE TITLE
mp_FineTuning

### ISSUE THREAD

**Issue by nielshanson** [hallamlab/metapathways2#2]
Alright, time to get serious about polishing some of this code to get it production ready. Here there are a collection of goals towards making the software more user-friendly and robust. These include:
- automatic **regression tests** for the python and C++ code
- **friendly and intelligent error messages** focusing on the likely problem and direct the user on how to fix it
- tighten up annotated and unannotated `gff` and `gbk` **file compatibility** and behaviour
- perhaps **additional support** for `fastq` files (not a big change from `fasta`)
- **windows compatibility** through virtual box
- **executable compatibility** and compilation
- **grid setup and use**

Other concerns should recognize that we want to quickly introduce these features in later:
- RPKM metric (likely v3.0 release)
- ML-TreeMap integration (likely v3.0 release)

**Comment by nyirock** [comment]
Hi, as for windows compatibility, do you still provide virtualbox image? I was going to try it first before installing, but the downloading link seem to be not working. Thanks.
