### ISSUE TITLE
Documentation provides no guidance on input files

### ISSUE THREAD

**Issue by taltman** [hallamlab/metapathways2#20]
The documentation doesn't explicitly state what input formats are accepted. 
- FASTA format? 
- DNA/RNA/oligo? 
- FASTQ? 
- Paired end reads mixed with non-paired end reads? 
- One file or multiple files?
- File naming and extension requirements?

I have a suspicion that my Issue with a zero-gene, zero-pathway PGDB is due to having my input file(s) in the wrong format.

**Comment by ariahahn** [comment]
Hi Tomer,

Nice to e-meet you too. The input is fasta (DNA or amino acid sequences).
Or gen bank. It doesn't handle fastq or RNA (it assumes if there are Us its
amino acid).

Thanks. We will update the documentation.

Aria
