### ISSUE TITLE
Feature Request: Support M5NR

### ISSUE THREAD

**Issue by taltman** [hallamlab/metapathways2#28]
Much better alternative than having users download all of RefSeq:

http://www.biomedcentral.com/1471-2105/13/141

A hand-full of other annotations pipelines make use of M5NR (MG-RAST, JGI, JCVI, etc.).
http://press.igsb.anl.gov/mg-rast/howto/m5nr-%E2%80%94-the-m5-non-redundant-protein-database/

**Comment by hallamlab** [comment]
thanks - we will consider this! we plan to improve downloading ease in 3.0
