### ISSUE TITLE
MP reports "Success" when run log reports PathoLogic error

### ISSUE THREAD

**Issue by taltman** [hallamlab/metapathways2#30]
The interface for the Run tab needs improvement. When the summary log text box says "BUILD_PGDB   SUCCESS", the detailed Run Log lower on the dialog reports an error (see full message below).

The GUI should catch that PathoLogic failed, and say "BUILD_PGDB   FAIL". The fact that a pipeline stage failed should be reported noisily, with big letters and red font. It is really hard to see that anything went wrong at all.

"RUNNING PATHOLOGIC  
ERROR   Failed to run Pathologic on input /afs/ir/users/t/a/taltman1/farmshare/third-party/bin/MetaPathways/v2.5/test/scaffolds/ptools// : 
INFO    Kill any other PathwayTools instance running on the machine and try again
ERROR   ERROR   Failed to run Pathologic on input /afs/ir/users/t/a/taltman1/farmshare/third-party/bin/MetaPathways/v2.5/test/scaffolds/ptools// : 
..... Redo Success!"

**Comment by hallamlab** [comment]
thanks - we are fixing this in the upcoming release
