### ISSUE TITLE
LAST raw results do not make it into {DB}.parsed.txt files

### ISSUE THREAD

**Issue by taltman** [hallamlab/metapathways2#32]
I have tried several things to generate a meaningful PathoLogic file using MP2. Even though I get LAST raw output files for COG, MetaCyc, and RefSeq in the blast_results directory, all of the *.parsed.txt versions of the file are empty (except for the first row of column headers). I think the problem lies here, but I don't know what to do. My PathoLogic file only contains six tRNA annotations (which are not using LAST, AFAICT).

Needless to say, the GUI shouldn't be so quick to state "SUCCESS" when this happens during the annotation phase.

**Comment by kishori82** [comment]
The input for pathologic are in the folder called ptools, at the same level as the blast_results folder

**Comment by taltman** [comment]
Thanks Kishori. As I wrote, I have found the PathoLogic input file (0.pf) in the ptools directory. The problem is that none of the LAST results make it into that file. Only six tRNA annotations make it in.

**Comment by kishori82** [comment]
Hi Tomer.  Please make sure when you were running the ANNOTATE_ORFS and PATHOLOGIC INPUT steps you had the databases in the Functional Annotation Parameters in the  Parameters tab selected. 
Also it is quite possible that the cutoffs on the min, evalue etc are filtering them out. Therefore, you may not have strong hits in your sample orfs or may be you need to relax the threshold. Thanks

**Comment by taltman** [comment]
Thanks. I will try tweaking the thresholds.

But please acknowledge that this should not be reported by the GUI as "SUCCESS". Obviously something has gone wrong if not a single annotation comes out of the COG, MetaCyc, and RefSeq databases, combined.

Furthermore, the GUI should detect this situation, and present the user with suggestions of what to try/toggle/tweak.

**Comment by kishori82** [comment]
Hi Tomer you are right we should have some sanity check for the results to flag such things or messages. I will think about putting in a fix. Probably I will think about it today and put many of the issues you raised in a couple of days.

**Comment by taltman** [comment]
I tried dialing down all of the thresholds down to their most permissive settings. No dice. The files are still empty. And yes, the database checkboxes are checked.

**Comment by kishori82** [comment]
One more thing. Please set PARSE FUNC SEARCH, ANNOTATE ORFS and PATHOLOGIC INPUT steps into redo (all 3) with the relaxed thresholds. Let me know if you see anything in the ptools/0.pf

**Comment by taltman** [comment]
Just tried it. Still no improvement.

**Comment by kishori82** [comment]
Hi Tomer, are you allowed to send me the output folder for sample that I can trouble shoot it and fix it?

**Comment by taltman** [comment]
Will do. Will send you link shortly via email.

**Comment by kishori82** [comment]
Thank you. I  am going to look into it today.

**Comment by taltman** [comment]
Thank you! Much appreciated.

**Comment by kishori82** [comment]
Hi Tomer,
I looked into your processed data and also, I reprocessed it myself. I got a few hits more than you did but they don't make it to the ptools because they hit hypothetical proteins in refeseq. If you would like to take a look at it I would be happy to send the files to you.

**Comment by taltman** [comment]
Thanks for looking into this for me.
I got 517 distinct functional protein hits for this data when I ran it through MG-RAST, so I find it hard to believe that there are no functional hits. The most obvious difference is that MG-RAST uses Blast. I'll try using MetaPathways with Blast, and see if this improves anything.

**Comment by taltman** [comment]
Hi Kishori,
I took another look at the set of files that I shared with you.
Notice the content in the COG and MetaCyc LAST output files. There are about 25 hits from MetaCyc, and 233 from COG. All of those hits are, by their very definition, not "hypothetical protein" annotations. How come they are not making it into the *.parsed.txt files, even with maximally-permissive settings?

**Comment by taltman** [comment]
Kishori,

I just tested MP again on E. coli K12 from EcoCyc 18.0 after figuring out the lastal errors. I'm still experiencing this where the LAST results are not making it into the parsed.txt files. The LAST output files are odd; they only have 3 columns, whereas the BLAST output has several columns. Is this what you get as well, testing the same software and data on your end?

BTW, I'm using the v2.5 GitHub versions of lastal and lastdb.

**Comment by kishori82** [comment]
Hi Tomer, 

Can you send  me one of the problematic LAST outputs?

Thanks
Kishori

**Comment by taltman** [comment]
Tarball link sent.

**Comment by nielshanson** [comment]
This and issue #40 are related. I can confirm that the ubuntu lastal and lastdb binaries were stale. I recompiled them on my Ubuntu 14.04 VirtualBox and that the `.LASTout.parsed.txt` makes with them look okay. Tomer, please check on your end if the following binaries work:
https://rawgit.com/hallamlab/metapathways2/master/executables/ubuntu/lastal
https://rawgit.com/hallamlab/metapathways2/master/executables/ubuntu/lastdb

**Comment by taltman** [comment]
Great to have you back, Niels!
I don't think this issue & #40 are directly related. I continue to have issues even using a working pair of lastal and lastdb. See my last few updates to this issue, and the tarball that I sent to you and Kishori.

Unless you are asserting that there's a bug with the lastal & lastdb pair that was causing them to produce garbage output files?

**Comment by nielshanson** [comment]
We added a new flag to the LAST -f2. Because we were conflicted about whether to ‘pollute/maintain’ the GitHub with compiled binaries, that folder has had a lot of turnover. Eventually we settled on they should be there, but somewhere along the line I must have picked up an old set from somewhere.

If you put -f2 in the old LAST code it will failsafe back to the 3-column output that you got, which is not something we use (too little information on hits).


On Feb 9, 2015, at 9:04 PM, Tomer Altman <notifications@github.com<mailto:notifications@github.com>> wrote:


Great to have you back, Niels!
I don't think this issue & #40<https://github.com/hallamlab/metapathways2/issues/40> are directly related. I continue to have issues even using a working pair of lastal and lastdb. See my last few updates to this issue, and the tarball that I sent to you and Kishori.

Unless you are asserting that there's a bug with the lastal & lastdb pair that was causing them to produce garbage output files?

**Comment by nielshanson** [comment]
Hey Tomer,

I think we actually got to the bottom of this one. It was actually a tricky bug to squash, but it has to do with us trying to calculate bit-scores in LAST akin to BLAST. Unforunately the old scores that LAST outputs were just the pure BLOSUM matrix score (S), while the BLAST bit-score (S') that is the corrected score based on the database size and composition parameters K and lambda.

S' = (lambda * S - ln(K)) / ln(2)

So in the case of LAST we were calculating score ratio BSR as S' / S., where S. is a perfect score which was deflating the value and causing a lot of results to be dropped. 

Anyhow now we've corrected it to evaluate S' / S' on the most recent code push. You should update your libs directory with the latest code and let us know if this improves your results with LAST.

**Comment by taltman** [comment]
Thanks for doing a deep dive into this bug!
Before I try to confirm the fix, can you give me instructions on how best to update the code? Should I download the latest tar-ball, as in the Wiki instructions, or should I start using the Git repo directly? What do you recommend?

**Comment by nielshanson** [comment]
I’ve packed it up as an updated release. Try using downloading this version of the code:
https://github.com/hallamlab/metapathways2/releases/tag/v2.5.1

Niels
