### ISSUE TITLE
Unpredictable X-windowing system error when launching MP2 from Ubuntu command-line

### ISSUE THREAD

**Issue by taltman** [hallamlab/metapathways2#33]
Sometimes when I try to launch the MP2 GUI from the Ubuntu command line, the following happens:
1. The GUI appears for an instant, then disappears
2. The following error message is echo'ed to the terminal:
   "QXcbConnection: XCB error: 152 (Unknown), sequence: 158, resource id: 0, major code: 142 (Unknown), minor code: 20"
3. The MetaPathways process continues to run, headless

**Comment by hallamlab** [comment]
Look for the fix in MP 3.0 coming soon!
