### ISSUE TITLE
Unclear how MP2 maps from RefSeq complete proteins to taxonomy

### ISSUE THREAD

**Issue by taltman** [hallamlab/metapathways2#35]
The FASTA deflines in the RefSeq complete proteins dataset only seem to contain the organism name as [Genus species]. Is this the basis for mapping from protein hit to taxon? This method would be error-prone. An explicit mapping file is provided by NCBI (protein GI numbers to NCBI Taxonomy DB IDs), but it seems to not be required by MP2. Any clarity would be great.

**Comment by taltman** [comment]
By clarity, I mean the mapping should be made explicit in the documentation.

**Comment by taltman** [comment]
Was this resolved?

**Comment by ariahahn** [comment]
Yes, this will be clear in the new documentation. Please note this was also
my list of issues yesterday...You would like to use a mapping file right?
We'd be happy to accommodate if you clarify how you'd like it done.
