### ISSUE TITLE
GUI, docs don't explain why input files not found

### ISSUE THREAD

**Issue by taltman** [hallamlab/metapathways2#36]
In trying to select the EcoCyc ecobase.nt FASTA nucleotide file for running through MP2, the GUI stated that "Could not find any samples to process!". Evidently, the code is looking for a short-list of acceptable file extensions. 

This is annoying. File extensions should be a suggestion, not a hard and fast rule. If it is a hard and fast rule, the GUI should state the reason it finds nothing. Plus, the documentation about acceptable input files should state the requirements explicitly.

**Comment by hallamlab** [comment]
wiki has been updated
