### ISSUE TITLE
Annotate PF files with source of annotation

### ISSUE THREAD

**Issue by taltman** [hallamlab/metapathways2#37]
Feature Request:

Since a user can select multiple databases, it would be helpful to link a particular entry in a PF file back to the database it came from. This can be encoded as a relationship link from the PF entry to the database used. This also allows for a single entry to link back to multiple databases, in the case of multiple hits.

**Comment by hallamlab** [comment]
this can be done by looking into the results file a file for
  each sample, located at
{samplename}/results/annotation_table/sample.2.txt which provides a detailed
  overview of the annotation for each orf in each database as well as
  score reflecting the confidence of the alignment and
  annotation - this will also tell you which database the annotation came from!
