### ISSUE TITLE
Multifunctional enzymes with more than one EC number not parsed correctly

### ISSUE THREAD

**Issue by taltman** [hallamlab/metapathways2#38]
Here's an entry from a MetaPathways-constructed PF file:

ID  scaffolds_208_0
NAME    scaffolds_208_0
STARTBASE   48900
ENDBASE 49205
PRODUCT dTDP-4-dehydrorhamnose 3,5-epimerase (EC 5.1.3.13) / reductase 1.1.1.133)
PRODUCT-TYPE    P
EC  5.1.3.13
//

Notice that even though the enzyme description includes two different EC numbers, only one makes it into its own EC line.

**Comment by taltman** [comment]
I should mention that I believe that the PathoLogic name -matcher will catch that second EC number, but I'm not sure. Something to check.

**Comment by hallamlab** [comment]
the pf file will be modified in future MP versions!
