### ISSUE TITLE
ERROR	lastal: the lastdb files are old: please re-run lastdb

### ISSUE THREAD

**Issue by taltman** [hallamlab/metapathways2#40]
After upgrading to 2.5.2, I got hit with this error in my test-run against E. coli chromosome. It's really annoying to have to rebuild the LAST index for RefSeq each time that I upgrade MP. Is there a way around this? Or at least a way to warn users? This should be documented at the very least, as a caveat for those upgrading MP.

**Comment by kishori82** [comment]
Hi Tomer,
Unless the LAST version has changed it should rebuild it. As far as I see it MP has not changed the last version. Once indexed please save a copy of it, in case MP is doing funny and unnecessarily rebuilding the index.

**Comment by taltman** [comment]
I think you meant to write, "it should not rebuild it"?

Something weird is definitely going on. Definitely not funny. Can you send me a minimal test case to try to figure out why it is not working correctly? Is that error coming from MP code, or from lastal itself?

I've send you more detailed output via email.

**Comment by kishori82** [comment]
Let me look at it now.

**Comment by taltman** [comment]
We traced the issue to an incompatible pairing of the lastdb and lastal executables bundled with MetaPathways2 in a special update tarball provided by Kishori. Test case not reproducible using released executables. Now testing full MetaPathways2 pipeline with tarball update, but using the released lastal and lastdb pairing.

**Comment by taltman** [comment]
Confirming that output via the pipeline looks sane.

I will resolve as soon as Kishori confirms that the current GitHub lastal & lastdb combo doesn't exhibit this problem.

**Comment by nielshanson** [comment]
Hi Tomer,
Back in the game again.

I can confirm that the compiled binaries for lastdb and lastal in the ubuntu directory were stale. I've rebuilt them on Ubuntu 14.04 LTS and tested and they produce correct lastDB.parsed.txt files on this end. I've pushed the code to the latest, so check to see if the binaries at the following executables work on your end. If it works okay I think we can close the issue.

https://rawgit.com/hallamlab/metapathways2/master/executables/ubuntu/lastal
https://rawgit.com/hallamlab/metapathways2/master/executables/ubuntu/lastdb

**Comment by taltman** [comment]
Thanks for looking into this, Niels.

I'll try to squeeze in some testing while awaiting the completion of my BLAST jobs.

**Comment by nielshanson** [comment]
Hey Tomer, 

Did you get a chance to check the binaries. They should be working properly, I've tried it on a few different machine running Ubuntu on this end.

**Comment by taltman** [comment]
Hi Niels,

I haven't had a chance to run my E. coli through MP2 using the updated last executables. Been busy using MP2 in Blast mode on my thesis work. :-) Will try to squeeze in a test.

In the mean-time, you can update MP2 to use the new version number output of Last to validate that there's a compatible pairing of lastdb and lastal installed. :-)
