### ISSUE TITLE
Command line not working

### ISSUE THREAD

**Issue by taltman** [hallamlab/metapathways2#41]
I tried to run MetaPathways from the command line. I got cryptic output, the program froze with no CPU activity. Not good. Redacted output here:

---

taltman1@corn29:~/farmshare/third-party/bin/MetaPathways/v2.5.2$ source MetaPathways_Python.2.5.1/MetaPathwaysrc 
Checking for Python and Perl:
Python found in  /usr/bin/python
Please set variable PYTHON_EXECUTABLE in file template_config.txt as:
PYTHON_EXECUTABLE  /usr/bin/python

Perl found in  /usr/bin/perl
Please set variable PERL_EXECUTABLE in file template_config.txt as:
PERL_EXECUTABLE  /usr/bin/perl

Adding installation folder of MetaPathways to PYTHONPATH
Your MetaPathways is installed in :
Please set variable METAPATHWAYS_PATH in file template_config.txt as:
PYTHONPATH  : /afs/ir/users/t/a/taltman1/farmshare/third-party/bin/MetaPathways/v2.5.2/MetaPathways_Python.2.5.1:/afs/ir/users/t/a/taltman1/farmshare/third-party/bin/MetaPathways/v2.5.2/MetaPathways_Python.2.5.1/libs:
METAPATHWAYS_PATH  /afs/ir/users/t/a/taltman1/farmshare/third-party/bin/MetaPathways/v2.5.2/MetaPathways_Python.2.5.1

taltman1@corn29:~/farmshare/third-party/bin/MetaPathways/v2.5.2$ time ./MetaPathways_Python.2.5.1/MetaPathways.py -i ~/assembly/ -o test/ -c template_config.txt -p template_param.txt -v -s scaffolds
from: can't read /var/mail/__future__
./MetaPathways_Python.2.5.1/MetaPathways.py:3: __author__: command not found
./MetaPathways_Python.2.5.1/MetaPathways.py:4: __copyright__: command not found
./MetaPathways_Python.2.5.1/MetaPathways.py:5: __credits__: command not found
./MetaPathways_Python.2.5.1/MetaPathways.py:6: __version__: command not found
./MetaPathways_Python.2.5.1/MetaPathways.py:7: __maintainer__: command not found
./MetaPathways_Python.2.5.1/MetaPathways.py:8: __status__: command not found
./MetaPathways_Python.2.5.1/MetaPathways.py:13: try:: command not found

**Comment by kishori82** [comment]
Hi Tomer,
Rerun the command as (with the python in front) 
python MetaPathways -i ..........

**Comment by taltman** [comment]
Yes, that works.

To get me to close the issue, please update the Wiki command-line instructions to include the leading 'python' in the command line:

https://github.com/hallamlab/metapathways2/wiki#running-metapathways-from-the-command-line-1

**Comment by nielshanson** [comment]
I've updated the docs to show this.

**Comment by taltman** [comment]
Thanks!
