### ISSUE TITLE
MetaPathways must include version numbers for bundled programs in release notes

### ISSUE THREAD

**Issue by taltman** [hallamlab/metapathways2#44]
When sharing findings from using MetaPathways, it will inevitably come up where someone wants to know which versions of programs like BLAST, or BWA, were used in computing one's findings. These software version numbers should be listed explicitly in the release notes for MP. This is essential for reproducible research.

**Comment by hallamlab** [comment]
this is listed in the papers! but yes, in the upcoming version this info will be more apparent!
