### ISSUE TITLE
"Need to remove the redundancy" echoed to terminal

### ISSUE THREAD

**Issue by taltman** [hallamlab/metapathways2#45]
I started MetaPathways in GUI mode. Peeking at the terminal, I saw the following message:
## 
## Need to remove the redundancy "scaffolds" "{full path redacted}/scaffolds/results/annotation_table/functional_and_taxonomic_table.txt" 

This seems like a message written by a developer to remind them to do something. This is just confusing for end-users.

**Comment by hallamlab** [comment]
we are looking into this message and will remove it in the upcoming 3.0 release
