### ISSUE TITLE
Results Tab has Amnesia

### ISSUE THREAD

**Issue by taltman** [hallamlab/metapathways2#46]
In the MP GUI, you can specify your input & output paths in the 'Stages' tab. Then, when you go to the 'Results' tab, it wants you to select a directory, as if it is not aware of the previously-entered directory.

The default set of output directories should be the exact same set specified from the 'Stages' tab.

**Comment by nielshanson** [comment]
Believe it or not this is actually a feature. We had users on this end that requested that the two were separated. Its because they want to run samples and view other samples at the same time. Confusing, but otherwise people found it restrictive.

**Comment by taltman** [comment]
Niels please reopen this ticket.

While it is reasonable to be able to change the 'results' directory, it is not reasonable to have it default to nothing, especially after the user has spent the time searching through the clunky directory browsing GUI in the 'Stages' tab. Please make the 'Results' directory default to the one specified in the 'Stages' tab.
