### ISSUE TITLE
Results tab: Unlabeled GUI elements are confusing

### ISSUE THREAD

**Issue by taltman** [hallamlab/metapathways2#47]
When you first come to the Results tab, you get three drop-down GUI elements in a row. Before selecting an output directory, only the first drop-down has any text associated with it. The others are blank, making it really confusing about what to do next.

In the empty grey area below the drop-down elements, there should be a helpful hint saying "Please select an MetaPathways output directory with one or more processed samples."

Yes, there are tool-tips for the GUI elements, but the hint will make it crystal clear about what the user should do next. The user shouldn't have to do a tool-tip treasure hunt.

**Comment by hallamlab** [comment]
an improved GUI is part if the upcoming 3.0 release! thanks!
