### ISSUE TITLE
LCAStar feature documented, but not visible in GUI, flatfiles

### ISSUE THREAD

**Issue by taltman** [hallamlab/metapathways2#48]
I'm excited to analyze the per-contig LCAStar results, as described on the Wiki. The problem is that I don't see the output in the Results tab's FUNC_TAX table, nor in the functional_and_taxonomic_table.txt. 

How do I access this feature?

The documentation will need to be improved to close this issue.

**Comment by nielshanson** [comment]
Hi Tomer,

I've cleared-up the documentation. Message me if you want to discuss LCA*.

**Comment by taltman** [comment]
Hi Niels,

I don't see any updated explanation for LCA* on the Wiki. In fact, the Wiki hasn't been updated in 2 days. Perhaps you haven't pushed the updates to GitHub yet (or perhaps GitHub wikis don't work that way)?

**Comment by nielshanson** [comment]
That's because I just clicked submit.
