### ISSUE TITLE
Selecting steps as 'redo' or 'yes' silently ignored

### ISSUE THREAD

**Issue by taltman** [hallamlab/metapathways2#52]
I've tried to select the steps via the GUI and via the command line. The steps in question are:

metapaths_steps:PATHOLOGIC_INPUT yes
metapaths_steps:CREATE_ANNOT_REPORTS yes
metapaths_steps:MLTREEMAP_CALCULATION yes

In both cases, the verbose output just says that the steps are "SKIPPING". 

Running the steps manually (based on the full command echoed in the output) seems to work correctly. But this is really annoying and I shouldn't have to do this.

**Comment by nielshanson** [comment]
Weird... I'll look into it.
