### ISSUE TITLE
Feature Request: Provide Contig-wide and Pathway-wide LCA values

### ISSUE THREAD

**Issue by taltman** [hallamlab/metapathways2#53]
Using LCA or some other method, it would be nice to annotate contigs and MetaCyc pathways with the LCA of all of the subsumed genes. Furthermore, it would be nice to have the WTD value generated as well. These should be ideally embedded in the ePGDB, or provided as a file that can easily be imported via SmartTables PTools feature.

**Comment by hallamlab** [comment]
A new tools came out that makes this possible - LCA star (hanson et al 2016). a new version of MP will soon be released however due to limited bandwidth of devlopers not all enhancements can be provided in each release! We have listed this a discussion topic!
