### ISSUE TITLE
Documentation on grid setup

### ISSUE THREAD

**Issue by rpelicae** [hallamlab/metapathways2#57]
Hello,
I want to try to use MetaPathways 2.5 where I perform the FUNC_SEARCH step on a remote compute cluster.
1. In the documentation of MetaPathways 1 it is said that computational tasks can be externalized providing the cluster uses the Sun Grid Engine scheduler. Is it for MetaPathways 2.5 possible to externalize to a cluster that uses TORQUE/Moab?
2. I understand that the cluster I want to use needs the blastp binary and the functional databases I want to search on. Is there a way to use the same configuration file as if I wanted to run the pipeline locally, i.e. without hard-coding the path to binaries and files each time?
3. Is there any manual intervention needed when one wants to externalize different steps of the pipeline, e.g. FUNC_SEARCH and MLTREEMAP_CALCULATION? How does the I/O work in MetaPathways when you externalize tasks?

Hope to hear from you,
Kind regards,
Rudy

**Comment by hallamlab** [comment]
we are moving toward using docker for MP - we are building a version should be easily used on multiple systems. I hope the new upcoming version will solve these problems
