### ISSUE TITLE
MP not using MetaCyc annotations correctly in *.pf file

### ISSUE THREAD

**Issue by taltman** [hallamlab/metapathways2#61]
The PF file creation in MP needs a lot of work. I hope that when some MP devs have some bandwidth, we can work to make better use of them.

One problem is that even despite using the MetaCyc reference database with Blast, the resulting MetaCyc hit is not being added to the correct field in order for PathoLogic to make use of it. There's a 'MetaCyc' attribute in PF files, and if provided with a MetaCyc reaction frame ID, it will assign the ORF directly, with zero ambiguity! Nice!

This should be added, as it will avoid people like me having to go through 50 ORFs in the PathoLogic "Assign Probable Enzyme" dialog manually...

**Comment by hallamlab** [comment]
as you know, a newer version of MP will soon be released and an alternative ptools input will be available
