### ISSUE TITLE
MP doesn't tell PTools to run the Transport Inference Parser

### ISSUE THREAD

**Issue by taltman** [hallamlab/metapathways2#63]
Running the Transport Inference Parser via batch PathoLogic will do a decent job predicting transporters based on the MP annotation. This also is a fairly fast operation. This should be turned on by default. Currently I've had to run this step manually.

**Comment by hallamlab** [comment]
yes, MP currently does not support all of the features in ptools. this is a large task as ptools is very powerful! a work in progress
