### ISSUE TITLE
Functional database installation

### ISSUE THREAD

**Issue by ctSkennerton** [hallamlab/metapathways2#69]
I'm a little confused about downloading some of the functional databases. I downloaded the file MetaPathwaysDBs.zip which contains the cog and metacyc databases. In the wiki though under the section "Installing Reference Databases" there are also links to the COGs ftp site and the metacyc website. Are these different databases that I need to install, aside from the ones included in the zip archive?

more questions:
1. the refseq database comes in multiple parts, do I need to concatenate them all into one file for use in metapathways?
2. Is it possible to get the KEGG database from 2011, is it hosted somewhere?
3. There is a link under the Carbohydrate-Active enZYmes (CAZy) database that talks about a specialized version for metapathways, however the link just points back to the wiki page

**Comment by taltman** [comment]
::Bump::

**Comment by ariahahn** [comment]
Hi Connor,

Any database can be used and you dont need to use all of them. So it's not
necessary to have a specific set of databases. Note that metacyc is
recommended if you wish to build epgdbs. Yes each database needs to be in a
single fasta file (including refseq). Start with the archive and see which
additional databases you'd like. the Kegg database is hosted by Kegg and by
googling Kegg database many resources and citations will come up. Let me
know how far you get and I'll do my best to help you get what you need. I
may be able to create new links for you to access some databases if they
are not in the archive. Let me know specifically which databases these
would be and I'll see if I have a copy.

**Comment by taltman** [comment]
I'm also eagerly awaiting the fixed CAZy database link. Thanks!

**Comment by taltman** [comment]
Ah, a working link to the CAZy database can be found on this page:

https://github.com/hallamlab/metapathways2/releases/tag/v2.5

MP team, can you please update the wiki page's link, now that I found it for you? :-p

**Comment by taltman** [comment]
Pro-tip: You can get a partial copy of the KEGG database from the HMP HMFUNC resource. Not sure if MetaPathways can use its formatted output for displaying pretty hierarchy reports, though...
