### ISSUE TITLE
Some contigs not present in functional_and_taxonomic_table.txt

### ISSUE THREAD

**Issue by taltman** [hallamlab/metapathways2#71]
Not all contigs present in the fasta file in the /preprocessed directory are represented in the functional_and_taxonomic_table.txt file. It's not because they do not have any annotations, because there are plenty of contigs that are labeled as "no-hits". It's not because they are too short, because there are shorter contigs represented in the file. 
Is it because they do not have any ORFs called?

It might be less ambiguous to just put in an entry, and use the controlled vocabulary term "no-orfs".

**Comment by hallamlab** [comment]
yes if nothing is predicted nothing is reported. others found it more difficult to do downstream analysis when these were reported. we based this on the behaviour of many other sofewares where 'null results' are not reported. thanks for the comment!
