### ISSUE TITLE
Addition of "/" in DB path

### ISSUE THREAD

**Issue by driscolc** [hallamlab/metapathways2#76]

**Comment by kishori82** [comment]
Dear Metapathways user,

I am not sure how the issue got resolved at your end, but it looks like it
you did solve it. Please let us know you still want me to look into it.

Thanks
Kishori

**Comment by driscolc** [comment]
I figured it out. Turned out to be a silly error on my part, which is why I
deleted the issue. Sorry for the inconvenience.

Connor

**Comment by kishori82** [comment]
No problem
