### ISSUE TITLE
Test dataset

### ISSUE THREAD

**Issue by gwilymh** [hallamlab/metapathways2#78]
Hi,
I would like to run MP on a test dataset to ensure it is working properly and that the databases it is using are correctly formatted.  There is a directory called "input" in the MP directory, that contains a bunch of fasta and genebank files. For some reason, there are also two empty files called _C1.fasta and C.fasta. Is there some explanation of what these files are for, and what results we can expect if we analyze them using MP.

Cheers,
G

**Comment by hallamlab** [comment]
Those should be removed - if they are empty nothing much will happen!
