### ISSUE TITLE
Makefile for executables/sources needs updating

### ISSUE THREAD

**Issue by taltman** [hallamlab/metapathways2#79]
The TARS var should list LAST.tar, not last-278.tar. last-278.tar doesn't exist.

**Comment by taltman** [comment]
Also, need to tweak the LAST line under buildall.

Also, should be rpkm_c, not rpkm.

**Comment by taltman** [comment]
Also, bwa tarball not handled at all.

**Comment by hallamlab** [comment]
we are working on a new, auto downloader and installer that will be available in the new release
