### ISSUE TITLE
MP2 Should utilize all CPUs when processing a set of samples, and spare CPUs are available

### ISSUE THREAD

**Issue by taltman** [hallamlab/metapathways2#83]
I gave MP2 a set of ten metagenomes to process on the command line. It is currently running Prodigal on a single CPU, and all other CPUs are idle. It should realize that it has spare CPU capacity at its disposal, and should start running Prodigal on all samples simultaneously.

**Comment by hallamlab** [comment]
this is great suggestion, thanks
