### ISSUE TITLE
MP2 doesn't recognize large formatted DBs due to chunk files

### ISSUE THREAD

**Issue by taltman** [hallamlab/metapathways2#85]
MP2 keeps on  trying to re-build already built DBs. I fixed the issue with the **temp** string, but it still persists in thinking that there are missing files.

I traced the error to the 'isDBformatted' in diagnoze.py [sic]. It should have the string '._' before the '\d_.' string in the regular expression checking for files. Now the code recognizes that the RefSeq and SEED formatted databases are present.

**Comment by hallamlab** [comment]
A new version addressing this issue will be available soon
