### ISSUE TITLE
MP2 happily reports, "THE END", but blastp keeps chugging away

### ISSUE THREAD

**Issue by taltman** [hallamlab/metapathways2#86]
The MetaPathways.py script has reported that it is done, but it appears that some MetaPathways_func_search.py sub-processes are still running, one-at-a-time. 

It should probably wait until all sub-processes have returned before gleefully reporting its completion.

Cheers,

~Tomer

**Comment by hallamlab** [comment]
A new version addressing this issue will be available soon
