### ISSUE TITLE
MP doesn't create incrementing locus ID for contig trna genes

### ISSUE THREAD

**Issue by taltman** [hallamlab/metapathways2#87]
Here is a selection of MetaPathways-created locus IDs for scaffold number 84:

scaffolds_84_0
scaffolds_84_4
scaffolds_84_5
scaffolds_84_tRNA

So, genes get sensible incrementing locus IDs, but the tRNA gene just gets the string 'trna'. What happens if there are two tRNA genes on one contig? Will the latest one overwrite the previous one?  

These tRNA locus IDs need to be incremented, too.

**Comment by hallamlab** [comment]
A new version of MP will be available shortly and address this issue
