### ISSUE TITLE
Truncating nucleotide sequences with ambiguous nucleotides

### ISSUE THREAD

**Issue by joshamilton** [hallamlab/metapathways2#90]
During pre-processing, MetaPathways shortens fasta sequences with ambiguous nucleotide codes. It appears to split the sequence at ambiguous nucleotides, and retains only the longest sub-sequence. This should be documented somewhere, and it would be nice to disable this behavior.

**Comment by taltman** [comment]
Funny, I just hit this bug the other day.
The solution is to go into the file MetaPathways_filter_input.py, and comment out the line that calls the function filter_sequence:

`# seqvalue = filter_sequence(seq)`

Instead, just assign seqvalue to seq:

`seqvalue = seq`

I've informed the developers of the bug, and they said that they're working on it. They'd have it faster if they'd be open to a pull request... :-)

**Comment by joshamilton** [comment]
Thanks! Nice to see where to modify the existing code so I don't have to write a workaround!
