### ISSUE TITLE
Issue with displaying results in GUI in MP v. 2.5.1.

### ISSUE THREAD

**Issue by GlassLabGT** [hallamlab/metapathways2#92]
Thanks very much for your hard work to make this software publicly available & for free. I have finally had a chance to run some of our genome assemblies through the pipeline. The run was successful, but I'm having problems visualizing the results in the MP results viewer. (This is really what I was hoping to use it for, as I was excited to have the annotations, phylogeny and contig viewer all together in one app.) I can get the DB file to open in the Pathway Tools software, but was hoping to use MP instead, as it appears to be a bit more user friendly. My view of the Results tab looks the same as the wiki (a blank page with no options to select anything for "Single-sample"). I can navigate to the output folder, but no choices appear in the "Select Samples" button. Thanks for your advice on how to get this working.

**Comment by michaeldubyu** [comment]
Hello, I am assuming you're referencing the documentation given at https://github.com/hallamlab/mp_tutorial/wiki/MetaPathways-v2.0-Installation-and-Usage-Instructions, and [this picture specifically](https://camo.githubusercontent.com/093679ad9cadab8eedbab385545b9e27aafab739/687474703a2f2f692e696d6775722e636f6d2f43716e774f6e552e706e673f31). Have you placed the formatted databases required for displaying results in the folder structure specified [in the steps](https://github.com/hallamlab/mp_tutorial/wiki/MetaPathways-v2.0-Installation-and-Usage-Instructions#reference-databases)?

**Comment by GlassLabGT** [comment]
Thanks for your fast response! Yes, that is the documentation I am referring to. Sorry, but I'm a bit confused. In version 2.5.1, I have "metapathways2-master" as the MP2 directory and "MetaPathways_DBs" as the database directory. I see the correct folders in the correct structure under "MetaPathways_DBs", but I don't see a "blastDB" folder anywhere. I am simply using the databases that came with the program (COG and MetaCyc for "functional", and LSURef for "taxonomic"). I will update them and add more databases later, but I wanted to make sure I could get it running first. I understand that since I haven't loaded KEGG, CAZY and SEED DBs, those results won't show, but shouldn't I be able to see the COG and MetaCyc tabs with the settings as they are?

**Comment by michaeldubyu** [comment]
If memory serves me correct, the release does not contain fully formatted database files. The database files we released were mostly for example, as at the time, they were in the tens of gigabytes when formatted locally. You would need to download and format the database and place them into their respective folders as required by the example.

**Comment by kishori82** [comment]
Hi Thanks for your comments. I will upload a video of how to use it in a
couple of days. I realized that this would help everyone out.

Regards
Kishori

**Comment by GlassLabGT** [comment]
Thanks Kishori, that would be greatly appreciated! I'm not sure if I'm using the correct DB files. They don't seem to be automatically formatting correctly, so I'm stuck now until I can add the DBs correctly (I was trying to use MetaCyc v20.0 and Silva SSU v123). Much appreciated!

**Comment by ariahahn** [comment]
Here is my set-up ( I have a lot of extra files but your should look
similar. First here is where MP is looking:

[image: Inline image 2]

Now here is what my file structure looks like inside

[image: Inline image 4]

On Mon, Jun 13, 2016 at 7:35 PM, jenniglass notifications@github.com
wrote:

> Thanks Kishori, that would be greatly appreciated! I'm not sure if I'm
> using the correct DB files. They don't seem to be automatically formatting
> correctly, so I'm stuck now until I can add the DBs correctly. Much
> appreciated!
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> https://github.com/hallamlab/metapathways2/issues/92#issuecomment-225764425,
> or mute the thread
> https://github.com/notifications/unsubscribe/AI6RqCvJlkh7sm-ps1R3xcDtclm5a-obks5qLhNygaJpZM4I02zo
> .

## 

Aria Hahn MSc
PhD Candidate
www.cupcakesandscience.com
Hallam Laboratory
http://www.cmde.science.ubc.ca/hallam/index.php

University of British Columbia
Department of Microbiology & Immunology
Life Sciences Centre
2350 Health Sciences Mall (Rm 2520)
Vancouver, BC Canada V6T 1Z3
T: 604-827-4216
F: 604-822-6041
ariahahn@interchange.ubc.ca
