### ISSUE TITLE
Installation of metapathways on linux cluster

### ISSUE THREAD

**Issue by ademenez** [hallamlab/metapathways2#93]
Hi,

I am trying to install metapathways on a Linux cluster (Linux Enterprise Server 12 (x86_64)) but I am struggling a bit. First I tried to install  metapathways2-2.5.2  and succeeded except getting the code to find the pathway-tools executable. The P tools executable does work on its own, but modifying the config_template file does not seem to work even though the error message that appears when I run metapathways.py does actually points out to the right folder where P tools is located. 

I then tried to install MetaPathways2.Ubuntu  but then when running ./Metapathways2 an error message came up saying the file  libQt5PrintSupport.so.5 cannot be found, even though it is present. 
Do you have any suggestions for me to install metapathways correctly? 

Thanks in advance,

Alexandre

**Comment by hallamlab** [comment]
Use 2.5.2 - Pathways tools can be tricky - if its the ptools executeable youre having trouble with please contact the developers of ptools- they are very responsive and knowledgable
