### ISSUE TITLE
failure to annotate metagenome

### ISSUE THREAD

**Issue by ademenez** [hallamlab/metapathways2#94]
Hi metapathway developers,

I am trying to run metapathways but having a few final hurdles to get through. When I run one sample, most tasks were completed successfully, but the final annotation against the database failed. Would you be able to offer me any advice to fix this? I copied the error message below.

Thanks in advance,

Alex

Error message:

WARNING Trying to format database 'COG_2013-12-27' for algorithm 'LAST'
INFO    Formatted database 'COG_2013-12-27' successfully for 'LAST'
WARNING Does not have map file '/dem056/metacyc_BLASTDB/BLASTDB///functional/formatted/COG_2013-12-27-names.txt' for 'COG_2013-12-27'
INFO    Successfully created  map file '/dem056/metacyc_BLASTDB/BLASTDB///functional/formatted/COG_2013-12-27-names.txt' for 'COG_2013-12-27'
RUNNING MetaPathways version 2.5.2
==============  RUNNING STEPS IN BLOCK 0 ================
###### 

PROCESSING INPUT /dem056/EBI_files/processed_reads/ProcessedReads/ERR911340_ProcessedReads.fasta [STEPS BLOCK 0]
PREPROCESSING THE INPUT                                     ..... Already Computed!
ORF PREDICTION                                              ..... Already Computed!
CREATING AMINO ACID SEQS FROM GFF FILE                      ..... Already Computed!
FILTER AMINO ACID SEQS                                      ..... Already Computed!
###### 

PROCESSING INPUT /dem056/EBI_files/processed_reads/ProcessedReads/ERR911340_ProcessedReads.fasta [STEPS BLOCK 1]
LASTING AMINO SEQS AGAINST COG_2013-12-27                   ..... Success!
###### 

PROCESSING INPUT /dem056/EBI_files/processed_reads/ProcessedReads/ERR911340_ProcessedReads.fasta [STEPS BLOCK 2]
COMPUTING REFSCORES FOR BITSCORE                            ..... Already Computed!
PARSING LAST OUTPUT FOR COG_2013-12-27                      ..... Success!
SCANNING FOR tRNA USING tRNA-Scan                           ..... Already Computed!
ANNOTATE ORFS
Processing database : COG_2013-12-27
ERROR : Failure to annotate in contig ERR911340_ProcessedReads_23959
Traceback (most recent call last):
  File "/dem056/metapathways2-master/libs/python_scripts/MetaPathways_annotate_fast.py", line 291, in write_annotation_for_orf
    attributes += ";" + "partial="+orf_dictionary[contig][candidate_orf_pos]['partial']
KeyError: 'partial'
None
..... Success!
GENBANK FILE                                                ..... Skipping [NO INPUT]!
PATHOLOGIC INPUT                                            ..... Skipping [NO INPUT]!
CREATING REPORT FILE FOR ORF ANNOTATION                     ..... Skipping [NO INPUT]!
RUNNING PATHOLOGIC                                          ..... Skipping [NO INPUT]!
RUNNING RPKM_CALCULATION                                    ..... Skipping [NO INPUT]!
            ***********
INFO : FINISHED PROCESSING THE SAMPLES
             THE END

**Comment by hallamlab** [comment]
A new version of MP will be available shortly and address this issue
