### ISSUE TITLE
Failure to annotate (KeyError: 'partial')

### ISSUE THREAD

**Issue by jessieluolab** [hallamlab/metapathways2#95]
Dear Admin,
Could you please help me out? It seems the *.gff file couldn't be generated due to the annotation error (KeyError: 'partial').

Thanks!
###### 

PROCESSING INPUT myproject/input//test_sample2.fasta [STEPS BLOCK 2]
COMPUTING REFSCORES FOR BITSCORE                            ..... Redo Success!
PARSING LAST OUTPUT FOR metacyc-v5-2011-10-21               ..... Redo Success!
PARSING LAST OUTPUT FOR CAZY_2014_09_04                     ..... Redo Success!
PARSING LAST OUTPUT FOR COG_2013-12-27                      ..... Redo Success!
SCANNING FOR tRNA USING tRNA-Scan                           ..... Already Computed!
ANNOTATE ORFS
Processing database : metacyc-v5-2011-10-21

Processing database : CAZY_2014_09_04

Processing database : COG_2013-12-27
ERROR : Failure to annotate in contig test_sample2_54
Traceback (most recent call last):
  File "/home/yhuang/software/MetaPathway/metapathways2-2.5.2/libs/python_scripts/MetaPathways_annotate_fast.py", line 291, in write_annotation_for_orf
    attributes += ";" + "partial="+orf_dictionary[contig][candidate_orf_pos]['partial']
KeyError: 'partial'
None
..... Redo Success!
PATHOLOGIC INPUT                                            ..... Skipping [NO INPUT]!
CREATING REPORT FILE FOR ORF ANNOTATION                     ..... Skipping [NO INPUT]!
RUNNING PATHOLOGIC                                          ..... Skipping [NO INPUT]!
RUNNING RPKM_CALCULATION                                    ..... Skipping [NO INPUT]!
            ***********
INFO : FINISHED PROCESSING THE SAMPLES
             THE END
            ***********

**Comment by kishori82** [comment]
Hi

I seem that the lasting stage did not complete or one of the stages did not
complete fully, possibly because of unexpected interrupt. Could you please
reprocess this samples and let me know?

Thanks
Kishori

**Comment by jessieluolab** [comment]
HI Kishori,

Thanks for your quick response. Please kindly find the test case input and
output from the attached. It was created by following the guide line in the
metapathways wiki page, "Question 11: I usually connect to my Linux/Unix
machine through a ssh shell. How do I run MetaPathways from a command line?"

Please note that the metapathways was installed in our Fedora22 linux
system via command line, so as the PathwayTools. We run metapathway from
the terminals using SSH (PuTTY and Xming). The keyerror:'partial' occurs
when running metapathways for test_sample2.

Thanks again for your help!

Best,
Yongjie

**Comment by kishori82** [comment]
Hi Yongjie,

I did not see any attachment with your email.

Thanks
Kishori

**Comment by hallamlab** [comment]
A new version of MP will be available shortly and address this issue
