### ISSUE TITLE
Documentation for MLtreemap

### ISSUE THREAD

**Issue by taltman** [hallamlab/metapathways2#96]
I'd like to get some clarification about what exactly is the output of MLtreemap in MetaPathways.

From a quick read about MLtreemap, it seems to provide a functional or taxonomic label for DNA sequences. Let me know if that is not the case.
- What taxonomic labels are used? NCBI Taxonomy? Some other phylogeny/taxonomy system?
- What functional labels are used?
- Is this applied at the contig, gene, or short-read level?
- Can you provide me an example output file?
- How are these taxonomic labels different than what LCA\* is computing?

**Comment by hallamlab** [comment]
See my answers below:
- What taxonomic labels are used? NCBI Taxonomy? Some other phylogeny/taxonomy system?
- MLTreeMap uses multiple sequence alignment and in the current version has about 14 trees. The taxonomic annotation is based on the tree life (version depends on which version of MLTreeMap you use - but its not the latest one that just came out). It has to be present in the tree to be found.
- What functional labels are used?
  -just functions within the 14 trees (eg. RuBisCO, Nitrogenase/NifD, Nitrogenase/NifH, and Methane Monooxygenase etc.) and this changes with the version as more are added
- Is this applied at the contig, gene, or short-read level?
  ORF
- Can you provide me an example output file?
  Yes, find attached some zip folders of an older sample of mine. These can then be run through an "image maker" to produce trees (also attached from a related sample)
- How are these taxonomic labels different than what LCA\* is computing?
- MLTreeMap uses multiple sequence alignment so it has to be in the tree and fit the alignment (so on average LCA can annotate ~80%) and MLTreeMap ~1% BUT what it does annotate is very accurate (and the resolution depends on the alignment)
