### ISSUE TITLE
command line metapathways fails to annotate

### ISSUE THREAD

**Issue by blancaverag** [hallamlab/metapathways2#98]
I am running metapathways2 command line and finding this error.

When executing 

> python MetaPathways.py -i /home/blanca/Contigs_same.fasta -o /home/blanca/metapa_commandLine -c config/template_config.txt -v -p config/template_param.txt 

It skips tRNA search and can't annotate a contig, apparently.

COMMAND : MetaPathways.py -i /home/blanca/Contigs_same.fasta -o /home/blanca/metapa_commandLine -c config/template_config.txt -v -p config/template_param.txt
WARNING	sequence for db  /home/database/blastdb/MetaPathways_DBs///functional/formatted/metacyc-v5-2011-10-21 not formatted
WARNING	Trying to format database 'metacyc-v5-2011-10-21' for algorithm 'LAST'
INFO	Formatted database 'metacyc-v5-2011-10-21' successfully for 'LAST'
WARNING	Does not have map file '/home/database/blastdb/MetaPathways_DBs///functional/formatted/metacyc-v5-2011-10-21-names.txt' for 'metacyc-v5-2011-10-21'
INFO	Successfully created  map file '/home/database/blastdb/MetaPathways_DBs///functional/formatted/metacyc-v5-2011-10-21-names.txt' for 'metacyc-v5-2011-10-21'
WARNING	sequence for db  /home/database/blastdb/MetaPathways_DBs///functional/formatted/COG_2013-12-27 not formatted
WARNING	Trying to format database 'COG_2013-12-27' for algorithm 'LAST'
INFO	Formatted database 'COG_2013-12-27' successfully for 'LAST'
WARNING	Does not have map file '/home/database/blastdb/MetaPathways_DBs///functional/formatted/COG_2013-12-27-names.txt' for 'COG_2013-12-27'
INFO	Successfully created  map file '/home/database/blastdb/MetaPathways_DBs///functional/formatted/COG_2013-12-27-names.txt' for 'COG_2013-12-27'
RUNNING MetaPathways version 2.5.1
==============  RUNNING STEPS IN BLOCK 0 ================

################################################

PROCESSING INPUT /home/blanca/Contigs_same.fasta [STEPS BLOCK 0] 

EXECUTED COMMAND : /home/programas/metapathways2-2.5.1/libs/python_scripts/MetaPathways_filter_input.py --min_length 180 --log_file /home/blanca/metapa_commandLine/Contigs_same/run_statistics//Contigs_same.nuc.stats  -i /home/blanca/Contigs_same.fasta -o  /home/blanca/metapa_commandLine/Contigs_same/preprocessed//Contigs_same.fasta -M /home/blanca/metapa_commandLine/Contigs_same/preprocessed//Contigs_same.mapping.txt -t nucleotide -L /home/blanca/metapa_commandLine/Contigs_same/run_statistics//Contigs_same.contig.lengths.txt
PREPROCESSING THE INPUT                                     ..... Success!

EXECUTED COMMAND : /home/programas/metapathways2-2.5.1/libs/python_scripts/MetaPathways_orf_prediction.py --prod_exec /home/programas/metapathways2-2.5.1//executables/ubuntu/prodigal --prod_m --prod_p meta --prod_f gff --prod_g 11 --prod_input /home/blanca/metapa_commandLine/Contigs_same/preprocessed//Contigs_same.fasta --prod_output /home/blanca/metapa_commandLine/Contigs_same/orf_prediction/Contigs_same.gff
ORF PREDICTION                                              ..... Success!

EXECUTED COMMAND : /home/programas/metapathways2-2.5.1/libs/python_scripts/MetaPathways_create_amino_sequences.py -g  /home/blanca/metapa_commandLine/Contigs_same/orf_prediction/Contigs_same.gff  -n /home/blanca/metapa_commandLine/Contigs_same/preprocessed//Contigs_same.fasta --output_nuc /home/blanca/metapa_commandLine/Contigs_same/orf_prediction//Contigs_same.fna --output_amino /home/blanca/metapa_commandLine/Contigs_same/orf_prediction//Contigs_same.faa --output_gff /home/blanca/metapa_commandLine/Contigs_same/orf_prediction//Contigs_same.unannot.gff
CREATING AMINO ACID SEQS FROM GFF FILE                      ..... Success!

EXECUTED COMMAND : /home/programas/metapathways2-2.5.1/libs/python_scripts/MetaPathways_filter_input.py  --min_length 60 --log_file /home/blanca/metapa_commandLine/Contigs_same/run_statistics//Contigs_same.amino.stats  -i /home/blanca/metapa_commandLine/Contigs_same/orf_prediction//Contigs_same.faa -o  /home/blanca/metapa_commandLine/Contigs_same/orf_prediction//Contigs_same.qced.faa -L /home/blanca/metapa_commandLine/Contigs_same/run_statistics//Contigs_same.orf.lengths.txt -t amino
FILTER AMINO ACID SEQS                                      ..... Success!

################################################
PROCESSING INPUT /home/blanca/Contigs_same.fasta [STEPS BLOCK 1] 
EXECUTED COMMAND : /home/programas/metapathways2-2.5.1//libs/python_scripts/MetaPathways_func_search.py --algorithm LAST --last_executable /home/programas/metapathways2-2.5.1//executables/ubuntu/lastal --last_o /home/blanca/metapa_commandLine/Contigs_same/blast_results//Contigs_same.metacyc-v5-2011-10-21.LASTout --last_f 2 --last_db /home/database/blastdb/MetaPathways_DBs///functional/formatted/metacyc-v5-2011-10-21 --last_query /home/blanca/metapa_commandLine/Contigs_same/orf_prediction//Contigs_same.qced.faa
LASTING AMINO SEQS AGAINST metacyc-v5-2011-10-21            ..... Success!

EXECUTED COMMAND : /home/programas/metapathways2-2.5.1//libs/python_scripts/MetaPathways_func_search.py --algorithm LAST --last_executable /home/programas/metapathways2-2.5.1//executables/ubuntu/lastal --last_o /home/blanca/metapa_commandLine/Contigs_same/blast_results//Contigs_same.COG_2013-12-27.LASTout --last_f 2 --last_db /home/database/blastdb/MetaPathways_DBs///functional/formatted/COG_2013-12-27 --last_query /home/blanca/metapa_commandLine/Contigs_same/orf_prediction//Contigs_same.qced.faa
LASTING AMINO SEQS AGAINST COG_2013-12-27                   ..... Success!

################################################

PROCESSING INPUT /home/blanca/Contigs_same.fasta [STEPS BLOCK 2] 

EXECUTED COMMAND : /home/programas/metapathways2-2.5.1//libs/python_scripts/MetaPathways_refscore.py   -o /home/blanca/metapa_commandLine/Contigs_same/blast_results//Contigs_same.refscores.LAST -i /home/blanca/metapa_commandLine/Contigs_same/orf_prediction//Contigs_same.qced.faa -a LAST
COMPUTING REFSCORES FOR BITSCORE                            ..... Redo Success!

EXECUTED COMMAND : /home/programas/metapathways2-2.5.1/libs/python_scripts/MetaPathways_parse_blast.py -d metacyc-v5-2011-10-21  -b /home/blanca/metapa_commandLine/Contigs_same/blast_results//Contigs_same.metacyc-v5-2011-10-21.LASTout -m /home/database/blastdb/MetaPathways_DBs///functional/formatted/metacyc-v5-2011-10-21-names.txt  -r  /home/blanca/metapa_commandLine/Contigs_same/blast_results//Contigs_same.refscores.LAST  --min_bsr 0.4  --min_score 20 --min_length 60 --max_evalue 0.000001 --algorithm LAST
PARSING LAST OUTPUT FOR metacyc-v5-2011-10-21               ..... Redo Success!

EXECUTED COMMAND : /home/programas/metapathways2-2.5.1/libs/python_scripts/MetaPathways_parse_blast.py -d COG_2013-12-27  -b /home/blanca/metapa_commandLine/Contigs_same/blast_results//Contigs_same.COG_2013-12-27.LASTout -m /home/database/blastdb/MetaPathways_DBs///functional/formatted/COG_2013-12-27-names.txt  -r  /home/blanca/metapa_commandLine/Contigs_same/blast_results//Contigs_same.refscores.LAST  --min_bsr 0.4  --min_score 20 --min_length 60 --max_evalue 0.000001 --algorithm LAST
PARSING LAST OUTPUT FOR COG_2013-12-27                      ..... Redo Success!

EXECUTED COMMAND : /home/programas/metapathways2-2.5.1//libs/python_scripts/MetaPathways_tRNA_scan.py --executable /home/programas/metapathways2-2.5.1//executables/ubuntu/trnascan-1.4 -o /home/blanca/metapa_commandLine/Contigs_same/results//tRNA//Contigs_same.tRNA.stats.txt -F /home/blanca/metapa_commandLine/Contigs_same/results//tRNA//Contigs_same.tRNA.fasta  -i /home/blanca/metapa_commandLine/Contigs_same/preprocessed//Contigs_same.fasta -T /home/programas/metapathways2-2.5.1/resources//TPCsignal  -D /home/programas/metapathways2-2.5.1/resources//Dsignal
SCANNING FOR tRNA USING tRNA-Scan                           ..... Skipping!

EXECUTED COMMAND : /home/programas/metapathways2-2.5.1/libs/python_scripts/MetaPathways_annotate_fast.py --input_gff  /home/blanca/metapa_commandLine/Contigs_same/orf_prediction//Contigs_same.unannot.gff -o /home/blanca/metapa_commandLine/Contigs_same/genbank//Contigs_same.annot.gff   --output-comparative-annotation /home/blanca/metapa_commandLine/Contigs_same/results//annotation_table//Contigs_same                     --algorithm LAST  -m /home/blanca/metapa_commandLine/Contigs_same/preprocessed//Contigs_same.mapping.txt -D /home/blanca/metapa_commandLine/Contigs_same/blast_results/ -s Contigs_same
ANNOTATE ORFS                                               
Processing database : COG_2013-12-27

Processing database : metacyc-v5-2011-10-21
ERROR : Failure to annotate in contig Contigs_same_38354
Traceback (most recent call last):
  File "/home/programas/metapathways2-2.5.1/libs/python_scripts/MetaPathways_annotate_fast.py", line 291, in write_annotation_for_orf
    attributes += ";" + "partial="+orf_dictionary[contig][candidate_orf_pos]['partial']
KeyError: 'partial'
None
..... Redo Success!

EXECUTED COMMAND : /home/programas/metapathways2-2.5.1/libs/python_scripts/MetaPathways_create_genbank_ptinput_sequin.py -g /home/blanca/metapa_commandLine/Contigs_same/genbank//Contigs_same.annot.gff -n /home/blanca/metapa_commandLine/Contigs_same/preprocessed//Contigs_same.fasta -p /home/blanca/metapa_commandLine/Contigs_same/orf_prediction//Contigs_same.qced.faa  --out-ptinput /home/blanca/metapa_commandLine/Contigs_same/ptools/
PATHOLOGIC INPUT                                            ..... Skipping [NO INPUT]!
MISSING INPUT LIST:
     /home/blanca/metapa_commandLine/Contigs_same/genbank//Contigs_same.annot.gff

EXECUTED COMMAND : /home/programas/metapathways2-2.5.1/libs/python_scripts/MetaPathways_create_reports_fast.py  --input-annotated-gff /home/blanca/metapa_commandLine/Contigs_same/genbank//Contigs_same.annot.gff  --input-kegg-maps /home/database/blastdb/MetaPathways_DBs///functional_categories/KO_classification.txt                  --input-cog-maps /home/database/blastdb/MetaPathways_DBs///functional_categories/COG_categories.txt --input-seed-maps /home/database/blastdb/MetaPathways_DBs///functional_categories/SEED_subsystems.txt --input-cazy-maps /home/database/blastdb/MetaPathways_DBs///functional_categories/CAZY_hierarchy.txt --output-dir /home/blanca/metapa_commandLine/Contigs_same/results//annotation_table/                  --ncbi-taxonomy-map /home/database/blastdb/MetaPathways_DBs///ncbi_tree/ncbi_taxonomy_tree.txt --ncbi-megan-map /home/database/blastdb/MetaPathways_DBs///ncbi_tree/ncbi.map -D /home/blanca/metapa_commandLine/Contigs_same/blast_results/ -s Contigs_same -a LAST
CREATING REPORT FILE FOR ORF ANNOTATION                     ..... Skipping [NO INPUT]!
MISSING INPUT LIST:
     /home/blanca/metapa_commandLine/Contigs_same/genbank//Contigs_same.annot.gff

EXECUTED COMMAND : /home/programas/metapathways2-2.5.1//libs/python_scripts/MetaPathways_run_pathologic.py --reactions /home/blanca/metapa_commandLine/Contigs_same/results//annotation_table//Contigs_same.metacyc.orf.annots.txt --ptoolsExec /home/programas/pathway-tools/pathway-tools -i /home/blanca/metapa_commandLine/Contigs_same/ptools// -p /home/programas/ptools_config/ptools-local/pgdbs/user/contigs_samecyc -s Contigs_same --wtd --annotation-table /home/blanca/metapa_commandLine/Contigs_same/results//annotation_table//functional_and_taxonomic_table.txt                 --ncbi-tree /home/database/blastdb/MetaPathways_DBs///ncbi_tree/ncbi_taxonomy_tree.txt --ncbi-megan-map /home/database/blastdb/MetaPathways_DBs///ncbi_tree/ncbi.map --output-pwy-table /home/blanca/metapa_commandLine/Contigs_same/results//pgdb//contigs_same.pwy.txt
RUNNING PATHOLOGIC                                          ..... Skipping!

EXECUTED COMMAND : /home/programas/metapathways2-2.5.1/libs/python_scripts/MetaPathways_rpkm.py -c /home/blanca/metapa_commandLine/Contigs_same/preprocessed//Contigs_same.fasta  --rpkmExec /home/programas/metapathways2-2.5.1//executables/ubuntu/rpkm --rpkmdir /home/blanca/reads -O /home/blanca/metapa_commandLine/Contigs_same/orf_prediction//Contigs_same.unannot.gff -o /home/blanca/metapa_commandLine/Contigs_same/results//rpkm/Contigs_same.orf_rpkm.txt --sample_name Contigs_same --stats /home/blanca/metapa_commandLine/Contigs_same/results//rpkm/Contigs_same.orf_rpkm_stats.txt --bwaFolder /home/blanca/metapa_commandLine/Contigs_same/bwa/ --bwaExec /home/programas/metapathways2-2.5.1//executables/ubuntu/bwa
RUNNING RPKM_CALCULATION                                    ..... Skipping!
            ***********                
INFO : FINISHED PROCESSING THE SAMPLES 
             THE END                   
            ***********                
Content of errors_warnings_log.txt 
#STEP	ORF_PREDICTION
#STEP	FUNC_SEARCH
#STEP	FUNC_SEARCH
#STEP	COMPUTE_REFSCORE
#STEP	PARSE_BLAST
#STEP	PARSE_BLAST
#STEP	ANNOTATE_ORFS
#STEP	PATHOLOGIC_INPUT
ERROR	Missing input /home/blanca/metapa_commandLine/Contigs_same/genbank//Contigs_same.annot.gff
ERROR	Missing input /home/blanca/metapa_commandLine/Contigs_same/genbank//Contigs_same.annot.gff
#STEP	CREATE_ANNOT_REPORTS
ERROR	Missing input /home/blanca/metapa_commandLine/Contigs_same/genbank//Contigs_same.annot.gff
ERROR	Missing input /home/blanca/metapa_commandLine/Contigs_same/genbank//Contigs_same.annot.gff

Content of metapathways_steps_log.txt 
==============  BEGIN RUN Contigs_same  BLOCK0 ================
PREPROCESS_INPUT	RUNNING
PREPROCESS_INPUT	SUCCESS
ORF_PREDICTION	RUNNING
ORF_PREDICTION	SUCCESS
ORF_TO_AMINO	RUNNING
ORF_TO_AMINO	SUCCESS
FILTER_AMINOS	RUNNING
FILTER_AMINOS	SUCCESS

==============  BEGIN RUN Contigs_same  BLOCK1 ================
FUNC_SEARCH:metacyc-v5-2011-10-21	RUNNING
FUNC_SEARCH:metacyc-v5-2011-10-21	SUCCESS
FUNC_SEARCH:COG_2013-12-27	RUNNING
FUNC_SEARCH:COG_2013-12-27	SUCCESS

==============  BEGIN RUN Contigs_same  BLOCK2 ================
COMPUTE_REFSCORES	RUNNING
COMPUTE_REFSCORES	SUCCESS
PARSE_FUNC_SEARCH:metacyc-v5-2011-10-21	RUNNING
PARSE_FUNC_SEARCH:metacyc-v5-2011-10-21	SUCCESS
PARSE_FUNC_SEARCH:COG_2013-12-27	RUNNING
PARSE_FUNC_SEARCH:COG_2013-12-27	SUCCESS
SCAN_tRNA	SKIPPED
ANNOTATE_ORFS	RUNNING
ANNOTATE_ORFS	SUCCESS
PATHOLOGIC_INPUT	MISSING_INPUT
CREATE_ANNOT_REPORTS	MISSING_INPUT
BUILD_PGDB	SKIPPED
COMPUTE_RPKM	SKIPPED

And here it is the contig it failes to annotate:

>Contigs_same_38354
ATTTGGGAAGACGTGCTtgATCGTTTcGATGAGCATGAAAATATAGAGCTGGCCTACCCAACcATGCGCATCTATCGCTAGTTAAGCTTATTAATTATTATCTTAAGTCATACCTTTCCTATGCTTAACTGTTATTTTTGATCGCCTGATCAACAATGAACAATAaTTTTATTGCTTGGATgGTACTTTTGGGCGTCCAAAAGTACCGAAAAAaCGCCGGACAAGgATTTGCGCGGCgGGGCACCGGTGccccTTGACGGGGTtAAAACAATGATCCTTCCcACTCAGAGATTACTTTCGGGATCTCATCGGTGTgTTTTTACCaTCACCCGCCTGCGCGTCCCCcTCGCAACCACCTGCCTCACAACTCCAAGgCCGTGGAgAAAATTTtCAtcAGATAGATAAAACgGcTGCGAATTTtATAAGGAAATAATCgGGGgTTTGGGGggTATTGCGGGAAAgTCGAGCGCAAAaGCGCTGGGTGTGGAAGAGCAGGGTTTAACGTACGCCTTTAGTCAGAACAATATCTCAAtACCCccgAtGGcTTTTCctGAAGGgATGCcTTtGgCaTtGGTtCTTTTttGGCCatCCAaAAAatGAaCACcTtCAGACTAAgTAACAGCaGCTTTCTGgATTTgTGCTTCTTAgAAAaGCAGCCGAtCCTATTTAACCTGAGTTcgatataaaTaATaataGAGATAtttcagaaagtc

**Comment by ariahahn** [comment]
Hi,

The tRNA skip is because this is set on your params file. You should be
able to set this. metapathways annotates orgs not contigs...I think it
might actually be an orf (and contigs is simply the name). It's seems the
orfs were annotated with other databases, correct?  Also try 2.52 (the
newest version).

Aria

**Comment by blancaverag** [comment]
Hi Aria, 

I have updated to 2.52.
Still having the same error. There are results under blast_results folder; COG and metacyc last results and the parsed files. However, there is nothing under the results/ folder. No pgdb, and annotation tables are empty.

Blanca

**Comment by hallamlab** [comment]
We will be releasing a new version shortly that will address this issue
